name: Build and Deploy Fleet Sourcing

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: glendenning-barn
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: usernamex36
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./data/fleet/Sourcing
          file: ./data/fleet/Sourcing/Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.io/usernamex36/fleet-sourcing:latest

      - name: Decode GCP Service Account
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" | base64 --decode > gcp_service_account.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: ${{ steps.decode-gcp.outputs.decoded-json }}

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2.0.1
        with:
          project_id: projectid-x

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker

      - name: Deploy to Cloud Run
        run: |
          # Deploy to Cloud Run with environment variables, including GCP service account
          gcloud run deploy fleet-sourcing \
            --execution-environment=gen2 \
            --image docker.io/usernamex36/fleet-sourcing:latest \
            --platform managed \
            --region us-west2 \
            --memory 2Gi \
            --cpu 1 \
            --allow-unauthenticated \
            --cpu-boost \
            --set-env-vars [ADESA_PASSWORD='NE7*p3!hNzKcbkgfL4mB',R2_SECRET_ACCESS_KEY='b25156e5c0b5aaa0de3dbf55d2386ee5fccdf46443e6513c11796465e2948739',GCP_SERVICE_ACCOUNT_JSON="$(cat gcp_service_account.json)"]
