name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/web  # Set the working directory for all run steps in this job

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'  # Using Node.js version 21

    - name: Check Current Working Directory
      run: pwd

    - name: List Directory Contents
      run: ls -l

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Vercel Deployment
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: jWhFKnfDuYLxEd4qD7vwuCPL
        vercel-org-id: team_NkmdgyTXKfVE5tqCg68snMPk
        vercel-project-id: jM1aImV93aERAfSCCFhpx6RH
        vercel-args: '--prod'
