name: Build Deploy Web

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/web
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Vercel Build
        run: npx vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Vercel Deploy
        run: npx vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --prod
