name: build and deploy fleet sourcing

on:
  push:
    branches:
      - main
#    paths:
#      - "data/fleet/Sourcing/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v1

      - name: login docker-hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: usernamex36
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./data/fleet/Sourcing
          file: ./data/fleet/Sourcing/Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.io/usernamex36/fleet-sourcing:latest

      - name: gcloud auth
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: '$(eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6InByb2plY3RpZC14IiwicHJpdmF0ZV9rZXlfaWQiOiIyYTVjZDg5NDk3NmYwZWZiMzQ3NjdiZTExMDA5ZTkyZDkwOTAzMDE1IiwicHJpdmF0ZV9rZXkiOiItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzJtbHN2TWxFaU90dVpcbmg4NnY2NUdPbVJQS2RRTGcybkZSWGxINGRyNVk3WnM1UGFUYld2WVI3Z3piL0hDQThRNm52NHZtdkNDb21sZ1NcbnIrT3cwaHp2b2Q1eFZtSlhoYlVsSG41MGpRQ1JHMDc4Nm92blBSUi9rbmZzN0NlN1RDVy9uUUFESkJ3aVovd01cblYxYlpBU0lUbFpIcEtxVklmMVZVeWVQMi80aGk3elF5aEJhMWlZSE5aYWorN092VzZPaGtYUHFaRlpXNEUwK0JcbjNVTHEwRGFrdzBtMDRoYUc3ZzZSUXNVYzBGYkc5c2UvcEF3OTNlUEdueVJxdXNxNUt5U001NGJkeWtVRFpLckFcbkJtaThuRnZhNmlsbEhwWHUyUFArUmY3ZDlMR1AycGhpYStUVG9vd1lDMkVONWdiQVlSaitRYjZ1TzE4blhsWGhcbkRvb01VMC83QWdNQkFBRUNnZ0VBUCtUN0N5UzhKeElaVFR1c0l2cDIwRUxZSGZ1YnFqcEZkSWRnZjJSdGJvaVZcbnpBMjU1ZGVLU3ZQVkpCVE0rUkZnWTJvdTllbldNNmp1TUh2RFhGZnBNQ0NmeVdERXdJTlV3MHhNUzFRYllxci9cbmxKZ3RwQmhIVit4VWNsNmYrSFhJcjZlc0hXMUJPdmpQeFRHNmZleGJsQ2ErQzZ5VWNTMjlHaElhNW82N2xvSXRcbks0b0IwQVBUc3VQWVc1OTBseXhFSDhHSEdYdEtHUDJldmV6a3RnamY4UGdpNXo1NU9VOWEzcHdpUG42N1J3VkxcbnR4d0luNFozS0k2NEpzK0dZN1dPejFtRjZqcTFIMnFaYUtNQlJxNzM5N2RkeUMrVU5hVmN2bXVDZFdlWkxDV1pcbnBhTHFmMkJoRm1ZSjd2VE9WOXZyVSt2UU45S3NHamh1UTJlRlV4cHVBUUtCZ1FEcGduTlYzSUVaMkZIRjI3K0NcbmtHcGZ1YUtiNEJ3UTNXVzhYVklGQXVRN09pQytOcHlkc0U0UXEzdnVRREh6WmNvT2R5d1VYSi82aTVqd1V4NzBcbmdXKzZGMU9sUms0QWxha3dqWFErWVlWMGk3VE5YRndWYkRrMkJUZ04yd0QveGt0b2tROERYZlZ1NXY5UjF5SFRcblJMcTgwRE5pNjNtOG9Sb1B4TUxmRXlRNXdRS0JnUURJTUxqY0VHS2NJSk5XWlFzMFBmU3lENG1xWUlpWUpEblZcbjBOM3BRUjlQMWhJdVExdVNCb2d3ZCtVYTRvQ0tLZ1ZhYnhqUWFTMlZIU0ZCZUtVY2d1S01rSXQ0NGFYN0xEcDJcbm9qN1I5NWtoQkVsdjNaQjhRU1RmZHpMUXpsT3IyZXFTc0pTbTJTMW1LMkxGK0gwTm0vUXpYajlBdEdQb1R1OUtcbjJIM0M0T1VndXdLQmdRQ1ZGMGwwcE5sNUd2ajdENWR6VWFuWmZMa3FOU2syUzJYTm92ZmZZejA5NDV0TVY2b2ZcbnRKWGpadG8yQUo3ai9UWEpqcVdDU3JHS1V0OVBjb0x0TWtlWDFaVCtqYWo0RHBaNy9aVWV6ejFhY0dqOFJlQTFcbmZXZjU2ZE1rWlpSNXVxNGpFWnM0VnlHQnNkT0srWVVMVTNLM1kyZXIzUlZaTHJOcEpnUVdVaTVyQVFLQmdHRnNcbmhLcGtOdmt3U1VQa1RMMlI0VUcrbWdxV2pDTXVqZzdtWlBpZFByWEZ3bmROUklVZU5LMFJ6Q2QzVDRMdHpFa2tcbmcvajVGcnZZdjFSemVEY1Y0MWJ4Q1U4ODBXQVpPQ0ovOXY2TDlyUEF1RlIraVZCUEM3ak04NmYyb1hXaXlhdTFcbno4SWJNeUxqdm1BRi9DWGhYY2laOTBKd0I2Y0lzeC9EbUFCOUhrVDlBb0dCQU9ZeDNxSnJ3RTRURVVicXZpZlNcbnV4TUxUbnAvNTBFWXA2VC9FMmc2MGZyaElKVktEQTc4MUtDc0NUUmxPVGtlZ01PNjlQSmcwd3NnZVpzT3lTVHhcblFURG9RQVZzWG5oQzhtbHFmNVdrTS9TTmlJMnAxTjFla0gwQjM3U2dVNW1yYXA1MkRRQURQVTI4cUxNUHVFdnVcbmJreTJuYUFKM0kwRWZkQzd0clh5K3ZnbFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwiY2xpZW50X2VtYWlsIjoic2VydmljZS1hY2NvdW50LW5hbWVAcHJvamVjdGlkLXguaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJjbGllbnRfaWQiOiIxMDM2NjkzODE1MTA4NzA2MDg1MDciLCJhdXRoX3VyaSI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwidG9rZW5fdXJpIjoiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLCJjbGllbnRfeDUwOV9jZXJ0X3VybCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvc2VydmljZS1hY2NvdW50LW5hbWUlNDBwcm9qZWN0aWQteC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInVuaXZlcnNlX2RvbWFpbiI6Imdvb2dsZWFwaXMuY29tIn0= | base64 --decode)'

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v2.0.1
        with:
          project_id: projectid-x

      - name: gclpud configure docker
        run: |
          gcloud auth configure-docker

      - name: deploy
        run: |
          gcloud run deploy fleet-sourcing \
            --execution-environment=gen2 \
            --image docker.io/usernamex36/fleet-sourcing:latest \
            --platform managed \
            --region us-west2 \
            --memory 2Gi \
            --cpu 1 \
            --allow-unauthenticated \
            --cpu-boost \
            --set-env-vars ADESA_PASSWORD=${{secrets.ADESA_PASSWORD}},R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }},GCP_SERVICE_ACCOUNT='{"type":"service_account","project_id":"projectid-x","private_key_id":"2a5cd894976f0efb34767be11009e92d90903015","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2mlsvMlEiOtuZ\nh86v65GOmRPKdQLg2nFRXlH4dr5Y7Zs5PaTbWvYR7gzb/HCA8Q6nv4vmvCComlgS\nr+Ow0hzvod5xVmJXhbUlHn50jQCRG0786ovnPRR/knfs7Ce7TCW/nQADJBwiZ/wM\nV1bZASITlZHpKqVIf1VUyeP2/4hi7zQyhBa1iYHNZaj+7OvW6OhkXPqZFZW4E0+B\n3ULq0Dakw0m04haG7g6RQsUc0FbG9se/pAw93ePGnyRqusq5KySM54bdykUDZKrA\nBmi8nFva6illHpXu2PP+Rf7d9LGP2phia+TToowYC2EN5gbAYRj+Qb6uO18nXlXh\nDooMU0/7AgMBAAECggEAP+T7CyS8JxIZTTusIvp20ELYHfubqjpFdIdgf2RtboiV\nzA255deKSvPVJBTM+RFgY2ou9enWM6juMHvDXFfpMCCfyWDEwINUw0xMS1QbYqr/\nlJgtpBhHV+xUcl6f+HXIr6esHW1BOvjPxTG6fexblCa+C6yUcS29GhIa5o67loIt\nK4oB0APTsuPYW590lyxEH8GHGXtKGP2evezktgjf8Pgi5z55OU9a3pwiPn67RwVL\ntxwIn4Z3KI64Js+GY7WOz1mF6jq1H2qZaKMBRq7397ddyC+UNaVcvmuCdWeZLCWZ\npaLqf2BhFmYJ7vTOV9vrU+vQN9KsGjhuQ2eFUxpuAQKBgQDpgnNV3IEZ2FHF27+C\nkGpfuaKb4BwQ3WW8XVIFAuQ7OiC+NpydsE4Qq3vuQDHzZcoOdywUXJ/6i5jwUx70\ngW+6F1OlRk4AlakwjXQ+YYV0i7TNXFwVbDk2BTgN2wD/xktokQ8DXfVu5v9R1yHT\nRLq80DNi63m8oRoPxMLfEyQ5wQKBgQDIMLjcEGKcIJNWZQs0PfSyD4mqYIiYJDnV\n0N3pQR9P1hIuQ1uSBogwd+Ua4oCKKgVabxjQaS2VHSFBeKUcguKMkIt44aX7LDp2\noj7R95khBElv3ZB8QSTfdzLQzlOr2eqSsJSm2S1mK2LF+H0Nm/QzXj9AtGPoTu9K\n2H3C4OUguwKBgQCVF0l0pNl5Gvj7D5dzUanZfLkqNSk2S2XNovffYz0945tMV6of\ntJXjZto2AJ7j/TXJjqWCSrGKUt9PcoLtMkeX1ZT+jaj4DpZ7/ZUezz1acGj8ReA1\nfWf56dMkZZR5uq4jEZs4VyGBsdOK+YULU3K3Y2er3RVZLrNpJgQWUi5rAQKBgGFs\nhKpkNvkwSUPkTL2R4UG+mgqWjCMujg7mZPidPrXFwndNRIUeNK0RzCd3T4LtzEkk\ng/j5FrvYv1RzeDcV41bxCU880WAZOCJ/9v6L9rPAuFR+iVBPC7jM86f2oXWiyau1\nz8IbMyLjvmAF/CXhXciZ90JwB6cIsx/DmAB9HkT9AoGBAOYx3qJrwE4TEUbqvifS\nuxMLTnp/50EYp6T/E2g60frhIJVKDA781KCsCTRlOTkegMO69PJg0wsgeZsOySTx\nQTDoQAVsXnhC8mlqf5WkM/SNiI2p1N1ekH0B37SgU5mrap52DQADPU28qLMPuEvu\nbky2naAJ3I0EfdC7trXy+vgl\n-----END PRIVATE KEY-----\n","client_email":"service-account-name@projectid-x.iam.gserviceaccount.com","client_id":"103669381510870608507","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/service-account-name%40projectid-x.iam.gserviceaccount.com","universe_domain":"googleapis.com"}'
