name: Deploy query result trigger

on:
  push:
    branches:
      - main
    paths:
      - "data/QueryResult/trigger/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.WORKERS_API_TOKEN }}
          workingDirectory: data/fleet/tokenRefresh
          secrets: |
            UPSTASH_REDIS_REST_TOKEN
        env:
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UPSTASH_REDIS_REST_URL: "https://usw1-curious-swan-33560.upstash.io"
