name: Deploy fleet DriveStateRefresh

on:
  push:
    branches:
      - main
#    paths:
#      - "data/fleet/DriveStateRefresh/**"

jobs:
  deploy:
    runs-on: glendenning-barn
    steps:
      - uses: actions/checkout@main

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.WORKERS_API_TOKEN }}
          workingDirectory: data/fleet/DriveStateRefresh
          secrets: |
            UPSTASH_REDIS_REST_TOKEN
            GOOGLE_MAPS_API_KEY
        env:
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
