name: fleet sourcing

on:
  push:
    branches:
      - main
#    paths:
#      - "data/fleet/Sourcing/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v1

      - name: login docker-hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: usernamex36
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./data/fleet/Sourcing
          file: ./data/fleet/Sourcing/Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.io/usernamex36/fleet-sourcing:latest

      - name: gcloud auth
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: '$(${{secrets.BASE64_GCP_SERVICE_ACCOUNT}} | base64 --decode)'

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v2.0.1
        with:
          project_id: projectid-x

      - name: gclpud configure docker
        run: |
          gcloud auth configure-docker

      - name: Decode and set GCP Service Account
        run: echo "GCP_SERVICE_ACCOUNT=$(echo '${{ secrets.BASE64_GCP_SERVICE_ACCOUNT }}' | base64 --decode)" >> $GITHUB_ENV

      - name: deploy
        run: |
          gcloud run deploy fleet-sourcing \
            --execution-environment=gen2 \
            --image docker.io/usernamex36/fleet-sourcing:latest \
            --platform managed \
            --region us-west2 \
            --memory 2Gi \
            --cpu 1 \
            --allow-unauthenticated \
            --cpu-boost \
            --set-env-vars ADESA_PASSWORD=${{ secrets.ADESA_PASSWORD }},R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }},GCP_SERVICE_ACCOUNT='${{ env.GCP_SERVICE_ACCOUNT }}'
