name: Trigger Fleet Sourcing Refresh

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes

jobs:
  triggerRefresh:
    runs-on: glendenning-barn

    steps:
      - name: Send Refresh Request
        run: |
          curl --location \
               --header 'Content-Type: application/json' \
               --data '{
                   "query": "?page=results&make=tesla&model=model+3&year=2021-2025&zipcode=94577&trim=model+3+-+performance&sort=endTime&order=asc"
               }' \
               'https://fleet-sourcing-fam6csc7aa-wl.a.run.app/refresh' || exit 1
          echo "Refresh request sent successfully."
