name: Schedule fleet sourcing refresh

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  makeWebRequest:
    runs-on: ubuntu-latest

    steps:
    - name: fleet sourcing refresh
      run: |
        curl -f -X POST "https://fleet-sourcing-fam6csc7aa-wl.a.run.app/refresh" \
             -H "Content-Type: application/json" \
             -d '{"body": "page=results&make=tesla&model=model+3&year=2021-2025&zipcode=94577&trim=model+3+-+performance&sort=endTime&order=asc"}' || exit 1
        echo "Request successful."
