name: Schedule fleet sourcing refresh

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  makeWebRequest:
    runs-on: ubuntu-latest

    steps:
    - name: fleet token refresh
      run: |
        curl -f -X POST "https://fleet-sourcing-fam6csc7aa-wl.a.run.app/refresh" \
             -H "Content-Type: application/json" \
             -d '{"body": "?page=results&make=tesla&model=model+3&year=2021-2024&zipcode=94577&sort=endTime&order=asc"}' || exit 1
        echo "Request successful."
