name:  SublicensePayment webhook

on:
  push:
    branches:
      - main
    paths:
      - "data/Sublicense/Payment/webhook/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.WORKERS_API_TOKEN }}
          workingDirectory: data/Sublicense/Payment/webhook
          secrets: |
            UPSTASH_REDIS_REST_TOKEN
            GOOGLE_MAPS_API_KEY
        env:
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
