name: ui-web-s 817 Rodney Dr San Leandro, CA 94577
on:
  push:
    branches:
      - main
    paths:
      - "ui/web-s/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUBLICENSE: 817 Rodney Dr San Leandro, CA 94577
    defaults:
      run:
        working-directory:  web-s-817-rodney-dr-san-leandro-ca-94577
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Rename directory
        run: mv ui/web-s web-s-817-rodney-dr-san-leandro-ca-94577
        working-directory: ${{ github.workspace }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Vercel Project Settings
        run: vercel pull --yes --scope teamname-x --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Vercel Build
        run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          IS_DEPLOYMENT: true
          BASE64_GCP_SERVICE_ACCOUNT: ${{ secrets.BASE64_GCP_SERVICE_ACCOUNT }}

      - name: Vercel Deploy
        run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          IS_DEPLOYMENT: true
          BASE64_GCP_SERVICE_ACCOUNT: ${{ secrets.BASE64_GCP_SERVICE_ACCOUNT }}
