name: build deploy web

on:
  push:
    branches:
      - main
    paths:
      - "ui/web/**"

jobs:
  build-deploy:
    runs-on: glendenning-barn
    defaults:
      run:
        working-directory: ui/web

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: nvm use 21
        uses: actions/setup-node@v2
        with:
          node-version: "21"

      - name: npm i
        run: npm install

      - name: pull
        run: vercel pull --yes --scope teamname-x --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: build
        run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: deploy
        run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} --prod
