name: Z build deploy 24327 Kome Rd Mi-Wuk Village, CA 95346
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/web-s
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rename directory
        run: mv ui/web-s web-s-24327-kome-rd-mi-wuk-village,-ca-95346

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Vercel Project Settings
        run: vercel pull --yes --scope teamname-x --environment=production --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Vercel Build
        run: npx vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Vercel Deploy
        run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }} --prod
